SP-2 increments
bgoldovsky/shortener pull request #5
Opened 2022-06-19 13:16 UTC by bgoldovsky

Инкременты второго спринта

2022-06-20 20:05 UTC, ASPecherkin requested changes
есть несколько замечаний

2022-06-20 20:05 UTC, ASPecherkin commented on internal/config/config.go
> +	cfg.serverAddress = serverAddress()
такой вариант рабочий, но не принят для выполения таких задач 

Обычно функцию делют явной (Init или ещё как) и уже её вызывают в main и ожидают ошибку, если что-то неудачно инциализировалась

2022-06-20 20:05 UTC, ASPecherkin commented on internal/middlewares/compressing.go
> +var gz *gzip.Writer
если есть способ избавить от глобальной переменной и init тут - лучше это сделать 

Так будет явно понятно где он инциализируется + проще будет писать тесты на такой код

2022-06-21 07:14 UTC, bgoldovsky commented on internal/config/config.go
> +	cfg.serverAddress = serverAddress()
Сделал инициализацию явной

2022-06-21 07:14 UTC, bgoldovsky commented on internal/middlewares/compressing.go
> +var gz *gzip.Writer
И тут тоже)

2022-06-21 07:15 UTC, closed without merging